[package]
name = "moni_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
tokio = { version = "1", features = ["full"] }  # Async runtime for real-time updates
crossterm = "0.28.1"
color-eyre = "0.6.3"
